DISEASES = [
"Large artery stiffness",
"Peripheral vessel",
"Blood pressure uncontrolled",
"Small and medium artery stiffness",
"Atherosclerosis",
"LDL Cholesterol",
"LV Hypertrophy",
"Metabolic syndrome",
"Insulin resistance",
"Beta cell function decreased",
"Blood glucose uncontrolled",
"Tissue inflammatory process",
"Hypothyroidism",
"Hyperthyroidism",
"Hepatic fibrosis",
"Chronic hepatitis",
"Respiratory disorders",
"Kidney function disorders",
"Digestive disorders",
"Major depression",
"ADHD children (learning)",
"Cerebral Dopamine decreased",
"Cerebral Serotonin decreased"
]